import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import NavMenu from "@/components/Nav/NavMenu";
import SessionProvider from "@/components/SessionProvider";
import SessionInfo from "@/components/SessionInfo";
import Recoil from "./utils/Recoil";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  

  return (
    <html lang="en">
      <body className={inter.className}>
          <SessionProvider session={session} >
            <Recoil  >
              <SessionInfo  />
              <main className="mx-auto text-2xl gap-2 text-text-light bg-bg">
                <NavMenu  />
                <div className="pt-[60px]">
                  {children}

                </div>
              </main>
            </Recoil>
          </SessionProvider>
      </body>
    </html>
  );
}
